### PR TITLE
Add DebugMiddleware

### PR DESCRIPTION
**Pull request by tomchristie**

### CODE REVIEW

**Comment by davidism** [comment]
I haven't had a chance to check out Uvicorn much yet, but does this work when there are multiple workers handling requests? How do you route debug requests to the worker that handled the original traceback? Handling multiple workers with the debugger is an open issue in Werkzeug.

**Comment by tomchristie** [comment]
> does this work when there are multiple workers handling requests?

Nope. I've made sure to reference that briefly in the documentation: http://www.uvicorn.org/toolkit/#debug

It matters less tho, since a single worker could be handling 1000's of concurrent requests.

I'll do some work on integrating `--debug` flags for the command line runner, and ensure that it errors when `--workers` is also set to > 1.  (We'll also get a plain `uvicorn.run(...)` command at some point.)

**Comment by tomchristie** [comment]
Also worth noting that the debugger doesn't bother making sure to eg. load the resources it uses asynchronously (at least for now). Shouldn't really be a noticeable issue tho, since you'll only ever block the task pool when an exception is raised to the debug middleware, and only for a few small disk loads.

**Comment by tomchristie** [comment]
Can kinda see how you might do it I guess, using something like redis pub/sub to mediate between the worker that gets the incoming request and the worker where the exception occurred.

**Pull request merged**
